//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoi4BlueprintBuilder.Localization.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hoi4BlueprintBuilder.Localization.Strings.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewFocusTreeFileView_CountryTag 的本地化字符串。
        /// </summary>
        public static string CreateNewFocusTreeFileView_CountryTag {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_CountryTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewFocusTreeFileView_CountryTagNotExist 的本地化字符串。
        /// </summary>
        public static string CreateNewFocusTreeFileView_CountryTagIsNotExist {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_CountryTagIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewFocusTreeFileView_DefaultFocusTree 的本地化字符串。
        /// </summary>
        public static string CreateNewFocusTreeFileView_DefaultFocusTree {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_DefaultFocusTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewFocusTreeFileView_FileName 的本地化字符串。
        /// </summary>
        public static string CreateNewFocusTreeFileView_FileName {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewFocusTreeFileView_FileNameAlreadyExist 的本地化字符串。
        /// </summary>
        public static string CreateNewFocusTreeFileView_FileNameAlreadyExist {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_FileNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewFocusTreeFileView_FocusTreeId 的本地化字符串。
        /// </summary>
        public static string CreateNewFocusTreeFileView_FocusTreeId {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_FocusTreeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewFocusTreeFileView_Title 的本地化字符串。
        /// </summary>
        public static string CreateNewFocusTreeFileView_Title {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewFocusView_CommonFocus 的本地化字符串。
        /// </summary>
        public static string CreateNewFocusView_CommonFocus {
            get {
                return ResourceManager.GetString("CreateNewFocusView_CommonFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewFocusView_FocusId 的本地化字符串。
        /// </summary>
        public static string CreateNewFocusView_FocusId {
            get {
                return ResourceManager.GetString("CreateNewFocusView_FocusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewFocusView_FocusIdAlreadyExist 的本地化字符串。
        /// </summary>
        public static string CreateNewFocusView_FocusIdAlreadyExist {
            get {
                return ResourceManager.GetString("CreateNewFocusView_FocusIdAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewFocusView_FocusType 的本地化字符串。
        /// </summary>
        public static string CreateNewFocusView_FocusType {
            get {
                return ResourceManager.GetString("CreateNewFocusView_FocusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewFocusView_SharedFocus 的本地化字符串。
        /// </summary>
        public static string CreateNewFocusView_SharedFocus {
            get {
                return ResourceManager.GetString("CreateNewFocusView_SharedFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewFocusView_TargetFileName 的本地化字符串。
        /// </summary>
        public static string CreateNewFocusView_TargetFileName {
            get {
                return ResourceManager.GetString("CreateNewFocusView_TargetFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_CreateNewFocusTree 的本地化字符串。
        /// </summary>
        public static string Menu_CreateNewFocusTree {
            get {
                return ResourceManager.GetString("Menu_CreateNewFocusTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_Save 的本地化字符串。
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
    }
}
