//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoi4BlueprintBuilder.Localization.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hoi4BlueprintBuilder.Localization.Strings.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common_Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common_Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common_Ok.
        /// </summary>
        public static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common_Rename.
        /// </summary>
        public static string Common_Rename {
            get {
                return ResourceManager.GetString("Common_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewFocusTreeFileView_CountryTag.
        /// </summary>
        public static string CreateNewFocusTreeFileView_CountryTag {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_CountryTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewFocusTreeFileView_CountryTagNotExist.
        /// </summary>
        public static string CreateNewFocusTreeFileView_CountryTagIsNotExist {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_CountryTagIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewFocusTreeFileView_DefaultFocusTree.
        /// </summary>
        public static string CreateNewFocusTreeFileView_DefaultFocusTree {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_DefaultFocusTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewFocusTreeFileView_FileName.
        /// </summary>
        public static string CreateNewFocusTreeFileView_FileName {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewFocusTreeFileView_FocusTreeId.
        /// </summary>
        public static string CreateNewFocusTreeFileView_FocusTreeId {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_FocusTreeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewFocusTreeFileView_Title.
        /// </summary>
        public static string CreateNewFocusTreeFileView_Title {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewFocusView_CommonFocus.
        /// </summary>
        public static string CreateNewFocusView_CommonFocus {
            get {
                return ResourceManager.GetString("CreateNewFocusView_CommonFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewFocusView_FocusId.
        /// </summary>
        public static string CreateNewFocusView_FocusId {
            get {
                return ResourceManager.GetString("CreateNewFocusView_FocusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewFocusView_FocusIdAlreadyExist.
        /// </summary>
        public static string CreateNewFocusView_FocusIdAlreadyExist {
            get {
                return ResourceManager.GetString("CreateNewFocusView_FocusIdAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewFocusView_FocusType.
        /// </summary>
        public static string CreateNewFocusView_FocusType {
            get {
                return ResourceManager.GetString("CreateNewFocusView_FocusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewFocusView_SharedFocus.
        /// </summary>
        public static string CreateNewFocusView_SharedFocus {
            get {
                return ResourceManager.GetString("CreateNewFocusView_SharedFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewFocusView_TargetFileName.
        /// </summary>
        public static string CreateNewFocusView_TargetFileName {
            get {
                return ResourceManager.GetString("CreateNewFocusView_TargetFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteFile_CanFindBack.
        /// </summary>
        public static string DeleteFile_CanFindBack {
            get {
                return ResourceManager.GetString("DeleteFile_CanFindBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteFile_EnsureFile.
        /// </summary>
        public static string DeleteFile_EnsureFile {
            get {
                return ResourceManager.GetString("DeleteFile_EnsureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteFile_EnsureFolder.
        /// </summary>
        public static string DeleteFile_EnsureFolder {
            get {
                return ResourceManager.GetString("DeleteFile_EnsureFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteFile_Failed.
        /// </summary>
        public static string DeleteFile_Failed {
            get {
                return ResourceManager.GetString("DeleteFile_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File_NameAlreadyExists.
        /// </summary>
        public static string File_NameAlreadyExists {
            get {
                return ResourceManager.GetString("File_NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenInExplorer.
        /// </summary>
        public static string File_OpenInExplorer {
            get {
                return ResourceManager.GetString("File_OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu_CopyFullPath.
        /// </summary>
        public static string Menu_CopyFullPath {
            get {
                return ResourceManager.GetString("Menu_CopyFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu_CopyRelativePath.
        /// </summary>
        public static string Menu_CopyRelativePath {
            get {
                return ResourceManager.GetString("Menu_CopyRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu_CreateNewFocusTree.
        /// </summary>
        public static string Menu_CreateNewFocusTree {
            get {
                return ResourceManager.GetString("Menu_CreateNewFocusTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu_Save.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenameFile_ErrorOccurs.
        /// </summary>
        public static string RenameFile_ErrorOccurs {
            get {
                return ResourceManager.GetString("RenameFile_ErrorOccurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenameFile_InvalidFileOrFolderName.
        /// </summary>
        public static string RenameFile_InvalidFileOrFolderName {
            get {
                return ResourceManager.GetString("RenameFile_InvalidFileOrFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenameFile_NameContainInvalidChar.
        /// </summary>
        public static string RenameFile_NameContainInvalidChar {
            get {
                return ResourceManager.GetString("RenameFile_NameContainInvalidChar", resourceCulture);
            }
        }
    }
}
