//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoi4BlueprintBuilder.Localization.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hoi4BlueprintBuilder.Localization.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Tag.
        /// </summary>
        public static string CreateNewFocusTreeFileView_CountryTag {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_CountryTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string CreateNewFocusTreeFileView_DefaultFocusTree {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_DefaultFocusTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string CreateNewFocusTreeFileView_FileName {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Tree ID.
        /// </summary>
        public static string CreateNewFocusTreeFileView_FocusTreeId {
            get {
                return ResourceManager.GetString("CreateNewFocusTreeFileView_FocusTreeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Id.
        /// </summary>
        public static string CreateNewFocusView_FocusId {
            get {
                return ResourceManager.GetString("CreateNewFocusView_FocusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Type.
        /// </summary>
        public static string CreateNewFocusView_FocusType {
            get {
                return ResourceManager.GetString("CreateNewFocusView_FocusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target FileName.
        /// </summary>
        public static string CreateNewFocusView_TargetFileName {
            get {
                return ResourceManager.GetString("CreateNewFocusView_TargetFileName", resourceCulture);
            }
        }
    }
}
