name: "Bug / 问题"
description: "Report a bug. / 报告一般问题。"
title: "[Bug]: "
body:
  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist / 前置检查"
      options:
        - label: "I have searched existing issues. / 我已搜索现有问题。"
          required: true
        - label: "I understand that attachments may contain personal information. / 我了解附件可能包含个人信息。"
          required: true
  - type: textarea
    id: content
    attributes:
      label: "Bug Details / 问题说明"
    validations:
      required: true
  - type: upload
    id: attachment
    attributes:
      label: "Attachments / 附件"
    validations:
      required: true
